# Homework 3  - Tryout pandas and numpy  

## Homework 3.1

### 3.1.a
Load the data from: http://opendata.dc.gov/datasets that I have include in this github   
into a dataframe.  ( The file has been is available in directory ./data/ccp_current_csv.csv )

In [20]:
import pandas as panda
data_sample=panda.read_csv('./data/ccp_current_csv.csv ')
print data_sample


                 STREET QUADRANT            FROMINTERSECTION  \
0               13th St       NW                  Kennedy St   
1                  S St       NW            North Capitol St   
2      Rhode Island Ave       NE            Brentwood Rd (W)   
3               Mill Rd       NW                     27th St   
4      Rhode Island Ave       NE            Brentwood Rd (M)   
5             Mellon St       SE                      5th St   
6          Nebraska Ave       NW              Northampton St   
7           Military Rd       NW                     30th St   
8          Nebraska Ave       NW                   Oliver St   
9               16th St       NW                  Alaska Ave   
10         Shoemaker St       NW                 Linnean Ave   
11         Underwood St       NW             Piney Branch Rd   
12             Elder St       NW                      7th St   
13              26th St       NW              Northampton St   
14               4th St       NW        

### 3.1.a  what is its shape and what does that mean?

In [3]:
data_sample.shape

(465, 27)

## Homework 3.2
 What are the number of rows in each 'QUADRANT' ?

In [21]:
data_sample['QUADRANT'].value_counts()

NW    195
NE    163
SE     84
BN     12
SW     11
Name: QUADRANT, dtype: int64

## Homework 3.3 - Array math demonstration 
For two arrarys  

a= [1,2,3,4]  type=float

b= [5,6,7,8]  type=float

Peform the following array operations using numpy   
( show both operational use of numpy and functional (example addition operation => + vs addition function => numbpy.add() )

### 3.3.1 addition a+b 

In [22]:
import numpy as np
from numpy import array
a = array( [1,2,3,4] )
b = array([5,6,7,8])
print a,b
print a+b #operational use


[1 2 3 4] [5 6 7 8]
[ 6  8 10 12]


In [23]:
np.add(a,b) #functional use

array([ 6,  8, 10, 12])

### 3.3.2 subtraction a-b

In [24]:
a-b #operational use

array([-4, -4, -4, -4])

In [25]:
np.subtract(a,b)#functional use

array([-4, -4, -4, -4])

### 3.3.3 multiplication a*b

In [26]:
a*b #operational use

array([ 5, 12, 21, 32])

In [27]:
np.multiply(a,b)#functional use

array([ 5, 12, 21, 32])

### 3.3.4 divsion a/b

In [28]:
a/b #operational use

array([0, 0, 0, 0])

In [29]:
np.divide(a,b) #functional use

array([0, 0, 0, 0])

### 3.3.5 modulo  a%b

In [30]:
a%b #operational use

array([1, 2, 3, 4])

In [31]:
np.mod(a,b) #functional use

array([1, 2, 3, 4])

### 3.3.6 power  a^b

In [33]:
a**b #operational use

array([    1,    64,  2187, 65536])

In [34]:
np.power(a,b) #functional use

array([    1,    64,  2187, 65536])

## Homework 3.4
Find your own data and load it into a dataframe

If loading own data means generating data by myself, then it is solved in the section- NumPy Practice which is below homework 3.5. All operations are performed on the data.

In [161]:
data_sample1=panda.read_csv('C:\Users\Sheshank Reddy\Downloads\iris.csv ')
data_sample1

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0           1.1          0.1     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
16            5.4          3.9           1.3          0.4     setosa
17            5.1          3.5           1.4          0.3     setosa
18            5.7          3.8           1.7          0.3     setosa
19            5.1          3.8           1.5          0.3     setosa
20            5.4          3.4           1.7          0.2     setosa
21            5.1          3.7           1.5          0.4     setosa
22            4.6          3.6           1.0          0.2     setosa
23            5.1          3.3           1.7          0.5     setosa
24            4.8          3.4           1.9          0.2     setosa
25            5.0          3.0           1.6          0.2     setosa
26            5.0          3.4           1.6          0.4     setosa
27            5.2          3.5           1.5          0.2     setosa
28            5.2          3.4           1.4          0.2     setosa
29            4.7          3.2           1.6          0.2     setosa
..            ...          ...           ...          ...        ...
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
125           7.2          3.2           6.0          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
128           6.4          2.8           5.6          2.1  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
133           6.3          2.8           5.1          1.5  virginica
134           6.1          2.6           5.6          1.4  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146

## Homework 3.5
Provide an interesting analysis of the data columns ( frequency or averages )

In [95]:
data_sample1.head(2)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [93]:
data_sample1.head(10) # we can access how many rows we want.

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [96]:
data_sample1.info(verbose=None, buf=None, max_cols=None, memory_usage=None, null_counts=None) 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal_length    150 non-null float64
sepal_width     150 non-null float64
petal_length    150 non-null float64
petal_width     150 non-null float64
species         150 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB


referred link - https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.info.html    

Parameters:     	
-verbose : {None, True, False}, optional      
Whether to print the full summary. None follows the display.max_info_columns setting. True or False overrides the      display.max_info_columns setting.    
-buf : writable buffer, defaults to sys.stdout   
-max_cols : int, default None      
Determines whether full summary or short summary is printed. None follows the display.max_info_columns setting.    
-memory_usage : boolean/string, default None     
Specifies whether total memory usage of the DataFrame elements (including index) should be displayed. None follows the display.memory_usage setting. True or False overrides the display.memory_usage setting. A value of ‘deep’ is equivalent of True, with deep introspection. Memory usage is shown in human-readable units (base-2 representation).        
-null_counts : boolean, default None     
Whether to show the non-null counts      
If None, then only show if the frame is smaller than max_info_rows and max_info_columns.    
If True, always show counts.     
If False, never show counts.     

In [15]:
data_sample1.describe()  #displays count, mean, standard deviation etc  numerical values in each dataframe column

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [102]:
data_sample1.loc[:10,["sepal_width","petal_length"]]   # displays specified rows for the specified columns.

sepal_width  petal_length
0           3.5           1.4
1           3.0           1.4
2           3.2           1.3
3           3.1           1.5
4           3.6           1.4
5           3.9           1.7
6           3.4           1.4
7           3.4           1.5
8           2.9           1.4
9           3.1           1.5
10          3.7           1.5

In [37]:
arr = np.array(data_sample1)
print arr

[[5.1 3.5 1.4 0.2 'setosa']
 [4.9 3.0 1.4 0.2 'setosa']
 [4.7 3.2 1.3 0.2 'setosa']
 [4.6 3.1 1.5 0.2 'setosa']
 [5.0 3.6 1.4 0.2 'setosa']
 [5.4 3.9 1.7 0.4 'setosa']
 [4.6 3.4 1.4 0.3 'setosa']
 [5.0 3.4 1.5 0.2 'setosa']
 [4.4 2.9 1.4 0.2 'setosa']
 [4.9 3.1 1.5 0.1 'setosa']
 [5.4 3.7 1.5 0.2 'setosa']
 [4.8 3.4 1.6 0.2 'setosa']
 [4.8 3.0 1.4 0.1 'setosa']
 [4.3 3.0 1.1 0.1 'setosa']
 [5.8 4.0 1.2 0.2 'setosa']
 [5.7 4.4 1.5 0.4 'setosa']
 [5.4 3.9 1.3 0.4 'setosa']
 [5.1 3.5 1.4 0.3 'setosa']
 [5.7 3.8 1.7 0.3 'setosa']
 [5.1 3.8 1.5 0.3 'setosa']
 [5.4 3.4 1.7 0.2 'setosa']
 [5.1 3.7 1.5 0.4 'setosa']
 [4.6 3.6 1.0 0.2 'setosa']
 [5.1 3.3 1.7 0.5 'setosa']
 [4.8 3.4 1.9 0.2 'setosa']
 [5.0 3.0 1.6 0.2 'setosa']
 [5.0 3.4 1.6 0.4 'setosa']
 [5.2 3.5 1.5 0.2 'setosa']
 [5.2 3.4 1.4 0.2 'setosa']
 [4.7 3.2 1.6 0.2 'setosa']
 [4.8 3.1 1.6 0.2 'setosa']
 [5.4 3.4 1.5 0.4 'setosa']
 [5.2 4.1 1.5 0.1 'setosa']
 [5.5 4.2 1.4 0.2 'setosa']
 [4.9 3.1 1.5 0.1 'setosa']
 [5.0 3.2 1.2 0.2 's

In [38]:
print(type(arr))

<type 'numpy.ndarray'>


In [59]:
print(arr.ndim)
print(arr.size)
print(arr.shape)
print(arr.dtype)

2
750
(150L, 5L)
object


# NumPy Practice    

referred link -https://github.com/sheshankvamshi4/PythonMachineLearning

# 'arange' and 'linspace'

In [55]:
print(np.arange(5,16))
print(np.arange(5,16,2))
print(np.arange(5,16,2.5))
print(np.arange(5,-16,-2))

[ 5  6  7  8  9 10 11 12 13 14 15]
[ 5  7  9 11 13 15]
[  5.    7.5  10.   12.5  15. ]
[  5   3   1  -1  -3  -5  -7  -9 -11 -13 -15]


In [58]:
print(np.linspace(5,16,2))
print(np.linspace(5,16,10))
print(np.linspace(5,16,12))


[  5.  16.]
[  5.           6.22222222   7.44444444   8.66666667   9.88888889
  11.11111111  12.33333333  13.55555556  14.77777778  16.        ]
[  5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.  16.]


# Zeroes, Ones, empty, and Identity matrix

In [109]:
print("only one parameter is passed, so it is considered as columns")
print(np.zeros(5))
print("3 by 4 matrix")
print(np.zeros((3,4)))

only one parameter is passed, so it is considered as columns
[ 0.  0.  0.  0.  0.]
3 by 4 matrix
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [110]:
print(np.ones(5))
print(np.ones((5,2)))
print("the matrix is multiplied by 5 ")
print(5*np.ones((3,5)))

[ 1.  1.  1.  1.  1.]
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
the matrix is multiplied by 5 
[[ 5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.]]


In [114]:
mat1 = np.eye(5) # we are printing an identity matrix using eye(). one parameter can be passed as dimension of matrix
print("Identity matrix of dimension", mat1.shape)
print(mat1)

('Identity matrix of dimension', (5L, 5L))
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


# Random number generation

In [64]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # using random.rand(x,y), where x,y can be our matrix dimensions.

Random number generation (from Uniform distribution)
[[ 0.4674776   0.61859584  0.63147216]
 [ 0.19219282  0.48423428  0.36504323]]


In [65]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 0.83749868  0.807979    2.20092469]
 [-0.74130297  1.22667028  0.69800795]
 [-0.16171743 -1.73949351 -0.10174331]
 [-0.69408656  1.60508493  0.46618384]]


In [115]:
print("Random integer vector:",np.random.randint(1,100,10)) #randint- it prints integers and we can specify how many we want.
print ("\nRandom integer matrix")
print(np.random.randint(1,100,(4,4))) #we can also get matrix with the syntax shown.
print(np.random.randint(1,7,20)) # instead of 20 we can pass the number we want.

('Random integer vector:', array([14, 72, 18, 75,  8, 31, 70, 50,  4, 19]))

Random integer matrix
[[63 57 66 73]
 [ 8 78 18 42]
 [47 84 64 53]
 [ 3 91 24 85]]
[3 4 5 1 2 5 3 1 5 3 1 6 5 1 5 3 6 1 6 5]


# Reshaping, min, max, sort

In [127]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5) # we can reshape into matrix using reshape().
c = a.reshape(6,5)
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)
print("a")
print(a)
print("b")
print(b)
print("c")
print(c)

A = ri(1,100,10) # Vector of random interegrs
print("A")
print(A)
print("after sort")
print(np.sort(A, kind='mergesort')) # we can sort using sort(variable given, kind = 'sort name').



('Shape of a:', (30L,))
('Shape of b:', (2L, 3L, 5L))
('Shape of c:', (6L, 5L))
a
[50 42 20 60 73 89 39 53 10 80 23 64 18 57 25 17 30 89  1 63 90 85 49 64 79
 69 81 42 26 82]
b
[[[50 42 20 60 73]
  [89 39 53 10 80]
  [23 64 18 57 25]]

 [[17 30 89  1 63]
  [90 85 49 64 79]
  [69 81 42 26 82]]]
c
[[50 42 20 60 73]
 [89 39 53 10 80]
 [23 64 18 57 25]
 [17 30 89  1 63]
 [90 85 49 64 79]
 [69 81 42 26 82]]
A
[50 25 51 77 29 10 21 90 51  7]
after sort
[ 7 10 21 25 29 50 51 51 77 90]


In [130]:
print("Max of a:", a.max()) #max ()- gives max value and min()- gives minimum value
print("Max of b:", b.min())
print("Max of c location:", c.argmax()) # argmax()- gives location of maximum value and argmin()- gives location of minimum value.
print("Max of c location:", c.argmin())

('Max of a:', 90)
('Max of b:', 1)
('Max of c location:', 20)
('Max of c location:', 18)


# Indexing and slicing

In [132]:
arr = np.arange(0,11)
print("Array:",arr)
print("Element at 7th index is:", arr[7])  #prints the value at location arr[7].
print("Elements from 3rd to 5th index are:", arr[3:6]) #prints the values at locations arr[3],arr[4],arr[5] not arr[6].
print("Elements up to 4th index are:", arr[:4]) #prints the values of location until arr[3].
print("Elements from last backwards are:", arr[-1::-1]) # prints elements in reverse or backward.

arr = np.arange(0,21,2)
print("New array:",arr)
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) #prints the values at location arr[2],arr[4],arr[9]. # we can learn how to access every value in the data set

('Array:', array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))
('Element at 7th index is:', 7)
('Elements from 3rd to 5th index are:', array([3, 4, 5]))
('Elements up to 4th index are:', array([0, 1, 2, 3]))
('Elements from last backwards are:', array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0]))
('New array:', array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20]))
('Elements at 2nd, 4th, and 9th index are:', array([ 4,  8, 18]))


In [141]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers",mat)

print("\nDouble bracket indexing\n")
print("Element in row index 1 and column index 2:", mat[1][2])

print("\nSingle bracket with comma indexing\n")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")

print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])

print("Subsetting sub-matrices")
print("Matrix with row indices 1 and 2 and column indices 3 and 4", mat[1:3,3:5])
print("Matrix with row indices 0 and 1 and column indices 1 and 3", mat[0:2,[1,3]])

('Matrix of random 2-digit numbers', array([[82, 91, 83, 15, 71],
       [62, 68, 73, 15, 99],
       [62, 30, 16, 40, 53]]))

Double bracket indexing

('Element in row index 1 and column index 2:', 73)

Single bracket with comma indexing

('Element in row index 1 and column index 2:', 73)

Row or column extract
----------------------
('Entire row at index 2:', array([62, 30, 16, 40, 53]))
('Entire column at index 3:', array([15, 15, 40]))
Subsetting sub-matrices
('Matrix with row indices 1 and 2 and column indices 3 and 4', array([[15, 99],
       [40, 53]]))
('Matrix with row indices 0 and 1 and column indices 1 and 3', array([[91, 15],
       [68, 15]]))


# Array operations (array-array, array-scalar, universal functions)

In [143]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("1st Matrix of random single-digit numbers",mat1)
print("2nd Matrix of random single-digit numbers",mat2)

print("Addition", mat1+mat2)
print("Multiplication", mat1*mat2)
print("Division", mat1/mat2)
print("Lineaer combination: 3*A - 2*B", 3*mat1-2*mat2)

print("Addition of a scalar (100)", 100+mat1)

print("Exponentiation, matrix cubed here", mat1**3)
print("Exponentiation, sq-root using pow function",pow(mat1,0.5))

('1st Matrix of random single-digit numbers', array([[8, 3, 7],
       [6, 9, 9],
       [2, 4, 3]]))
('2nd Matrix of random single-digit numbers', array([[7, 6, 1],
       [9, 6, 7],
       [8, 1, 2]]))
('Addition', array([[15,  9,  8],
       [15, 15, 16],
       [10,  5,  5]]))
('Multiplication', array([[56, 18,  7],
       [54, 54, 63],
       [16,  4,  6]]))
('Division', array([[1, 0, 7],
       [0, 1, 1],
       [0, 4, 1]]))
('Lineaer combination: 3*A - 2*B', array([[ 10,  -3,  19],
       [  0,  15,  13],
       [-10,  10,   5]]))
('Addition of a scalar (100)', array([[108, 103, 107],
       [106, 109, 109],
       [102, 104, 103]]))
('Exponentiation, matrix cubed here', array([[512,  27, 343],
       [216, 729, 729],
       [  8,  64,  27]]))
('Exponentiation, sq-root using pow function', array([[ 2.82842712,  1.73205081,  2.64575131],
       [ 2.44948974,  3.        ,  3.        ],
       [ 1.41421356,  2.        ,  1.73205081]]))


# NumPy mathematical functions on array

In [145]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("1st Matrix of random single-digit numbers",mat1)
print("2nd Matrix of random single-digit numbers",mat2)

print("Sq-root of 1st matrix using np", np.sqrt(mat1))
print("Exponential power of 1st matrix using np", np.exp(mat1))
print("10-base logarithm on 1st matrix using np", np.log10(mat1))
print("Modulo reminder using np", np.fmod(mat1,mat2))

('1st Matrix of random single-digit numbers', array([[1, 5, 3],
       [1, 4, 3],
       [7, 8, 4]]))
('2nd Matrix of random single-digit numbers', array([[8, 4, 6],
       [4, 2, 6],
       [2, 9, 2]]))
('Sq-root of 1st matrix using np', array([[ 1.        ,  2.23606798,  1.73205081],
       [ 1.        ,  2.        ,  1.73205081],
       [ 2.64575131,  2.82842712,  2.        ]]))
('Exponential power of 1st matrix using np', array([[  2.71828183e+00,   1.48413159e+02,   2.00855369e+01],
       [  2.71828183e+00,   5.45981500e+01,   2.00855369e+01],
       [  1.09663316e+03,   2.98095799e+03,   5.45981500e+01]]))
('10-base logarithm on 1st matrix using np', array([[ 0.        ,  0.69897   ,  0.47712125],
       [ 0.        ,  0.60205999,  0.47712125],
       [ 0.84509804,  0.90308999,  0.60205999]]))
('Modulo reminder using np', array([[1, 1, 3],
       [1, 0, 3],
       [1, 8, 0]]))


# NumPy basic statistics on array

In [151]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("1st Matrix of random single-digit numbers",mat1)
print("2nd Matrix of random single-digit numbers",mat2)

print("Sum of all numbers in 1st matrix",np.sum(mat1))
print("Sum of all numbers in columns of 1st matrix",np.sum(mat1,axis=0))
print("Sum of all numbers in rows of 1st matrix",np.sum(mat1,axis=1))
print("Product of all numbers in rows of 1st matrix",np.prod(mat1,axis=1))
print("Product of all numbers in columns of 2nd matrix",np.prod(mat2,axis=0))
print("Mean of all numbers in 1st matrix",np.mean(mat1))
print("Standard deviation of all numbers in 1st matrix",np.std(mat1))

mat1 = np.array(ri(1,100,9)).reshape(3,3)
print("Modified matrix of random numbers from 1 to 99",mat1)
print("Standard deviation of all numbers in the modified matrix, a larger number",np.std(mat1))
print("Variance of all numbers in the modified matrix, a larger number",np.var(mat1))
print("Median of all numbers in the modified matrix",np.median(mat1))

mat2 = np.array(ri(1,100,50)).reshape(10,5)
print("Modified matrix of 50 random numbers from 1 to 99",mat2)
print("Standard deviation along the columns in the modified matrix",np.std(mat2,axis=0))

mat1 = np.array(ri(1,100,20)).reshape(4,5)
print("Modified matrix of random numbers from 1 to 49",mat1)
print("Flattened and sorted matrix (as vector)",np.sort(mat1.reshape(1,20)))
print("50th percentile of all numbers in the modified matrix",np.percentile(mat1,50))
print("90th percentile of all numbers in the modified matrix",np.percentile(mat1,90))

('1st Matrix of random single-digit numbers', array([[4, 8, 9],
       [1, 1, 7],
       [9, 9, 3]]))
('2nd Matrix of random single-digit numbers', array([[3, 9, 5],
       [5, 8, 2],
       [8, 8, 8]]))
('Sum of all numbers in 1st matrix', 51)
('Sum of all numbers in columns of 1st matrix', array([14, 18, 19]))
('Sum of all numbers in rows of 1st matrix', array([21,  9, 21]))
('Product of all numbers in rows of 1st matrix', array([288,   7, 243]))
('Product of all numbers in columns of 2nd matrix', array([120, 576,  80]))
('Mean of all numbers in 1st matrix', 5.666666666666667)
('Standard deviation of all numbers in 1st matrix', 3.2317865716108862)
('Modified matrix of random numbers from 1 to 99', array([[89, 21, 54],
       [14, 42, 74],
       [82, 47, 22]]))
('Standard deviation of all numbers in the modified matrix, a larger number', 26.094320842798602)
('Variance of all numbers in the modified matrix, a larger number', 680.91358024691363)
('Median of all numbers in the modified 

# Pandas Practice

In [77]:

labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

print ("Labels:", labels)
print("My data:", my_data)
print("Dictionary:", d)

('Labels:', ['a', 'b', 'c'])
('My data:', [10, 20, 30])
('Dictionary:', {'a': 10, 'c': 30, 'b': 20})


In [78]:
panda.Series(data=my_data)

0    10
1    20
2    30
dtype: int64

In [79]:
panda.Series(data=my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [82]:
panda.Series(arr, labels)

a    10
b    20
c    30
dtype: int32

In [83]:
panda.Series(d)

a    10
b    20
c    30
dtype: int64

In [153]:
print ("Holding numerical data")
print(panda.Series(arr))
print ("Holding text labels")
print(panda.Series(labels))
print ("Holding functions")
print(panda.Series(data=[sum,len]))
print ("Holding objects from a dictionary")
print(panda.Series(data=[d.keys, d.items, d.values]))

Holding numerical data
0      0
1      2
2      4
3      6
4      8
5     10
6     12
7     14
8     16
9     18
10    20
dtype: int32
Holding text labels
0    a
1    b
2    c
dtype: object
Holding functions
0    <built-in function sum>
1    <built-in function len>
dtype: object
Holding objects from a dictionary
0    <built-in method keys of dict object at 0x0000...
1    <built-in method items of dict object at 0x000...
2    <built-in method values of dict object at 0x00...
dtype: object


# Indexing and slicing


In [159]:
ser1 = panda.Series([1,2,3,4],['CA', 'OR', 'CO', 'AZ'])
ser2 = panda.Series([1,2,5,4],['CA', 'OR', 'NV', 'AZ'])

print ("Indexing by name of the item/object (string identifier)")
print("Value for CA in ser1:", ser1['CA'])
print("Value for AZ in ser1:", ser1['AZ'])
print("Value for NV in ser2:", ser2['NV'])

print ("Indexing by number (positional value in the series)" )
print("Value for CA in ser1:", ser1[0])
print("Value for AZ in ser1:", ser1[3])
print("Value for NV in ser2:", ser2[2])

print ("Indexing by a range")
print ("Value for OR, CO, and AZ in ser1:",ser1[1:4])

Indexing by name of the item/object (string identifier)
('Value for CA in ser1:', 1)
('Value for AZ in ser1:', 4)
('Value for NV in ser2:', 5)
Indexing by number (positional value in the series)
('Value for CA in ser1:', 1)
('Value for AZ in ser1:', 4)
('Value for NV in ser2:', 5)
Indexing by a range
('Value for OR, CO, and AZ in ser1:', OR    2
CO    3
AZ    4
dtype: int64)


# Adding/Merging two series with common indices


In [160]:
ser1 = panda.Series([1,2,3,4],['CA', 'OR', 'CO', 'AZ'])
ser2 = panda.Series([1,2,5,4],['CA', 'OR', 'NV', 'AZ'])
ser3 = ser1+ser2

print ("After adding the two series, the result looks like this.")
print(ser3)
print("Python tries to add values where it finds common index name, and puts NaN where indices are missing")

print ("The idea works even for multiplication.")
print (ser1*ser2)

print ("Or even for combination of mathematical operations!")
print (np.exp(ser1)+np.log10(ser2))

After adding the two series, the result looks like this.
AZ    8.0
CA    2.0
CO    NaN
NV    NaN
OR    4.0
dtype: float64
Python tries to add values where it finds common index name, and puts NaN where indices are missing
The idea works even for multiplication.
AZ    16.0
CA     1.0
CO     NaN
NV     NaN
OR     4.0
dtype: float64
Or even for combination of mathematical operations!
AZ    55.200210
CA     2.718282
CO          NaN
NV          NaN
OR     7.690086
dtype: float64
